/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taemincho_feature_Chroma */

#ifndef _Included_com_taemincho_feature_Chroma
#define _Included_com_taemincho_feature_Chroma
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taemincho_feature_Chroma
 * Method:    create
 * Signature: (IIIIF)J
 */
JNIEXPORT jlong JNICALL Java_com_taemincho_feature_Chroma_create
  (JNIEnv *, jobject, jint, jint, jint, jint, jfloat);

/*
 * Class:     com_taemincho_feature_Chroma
 * Method:    genChroma
 * Signature: (J[FI[F)V
 */
JNIEXPORT void JNICALL Java_com_taemincho_feature_Chroma_genChroma
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jfloatArray);

/*
 * Class:     com_taemincho_feature_Chroma
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_taemincho_feature_Chroma_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
